spring.application.name=Assignment_Backend

# ===============================
# SERVER CONFIGURATION
# ===============================

# Spring Boot application port
server.port=8080

# ===============================
# H2 DATABASE CONFIGURATION
# ===============================

# H2 database URL
spring.datasource.url=jdbc:h2:mem:testdb

# H2 database driver
spring.datasource.driverClassName=org.h2.Driver

# H2 database username
spring.datasource.username=deepu

# H2 database password
spring.datasource.password=

# H2 dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# ===============================
# H2 CONSOLE CONFIGURATION
# ===============================

# Enable H2 console
spring.h2.console.enabled=true

# H2 console path
spring.h2.console.path=/h2-console

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================

# Automatically create/update tables
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in console
spring.jpa.show-sql=true

# Format SQL queries
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true

# ===============================
# STATIC RESOURCE CONFIGURATION
# ===============================

# Disable cache during development
spring.web.resources.cache.period=0


# ===============================
# LOGGING
# ===============================

logging.level.org.springframework=INFO
